version: "3.9"

services:
  sale:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: "telemetry-sale"
    restart: on-failure
    expose:
      - 8325
    networks:
      - web-network

networks:
  web-network:
    external: true
    name: web-external-network